#!/bin/bash
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/bg-\[#0A0A0B\]/bg-bg/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/bg-\[#131316\]/bg-surface/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/bg-\[#1A1A1E\]/bg-surface-hover/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/border-white\/5/border-border/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/border-white\/10/border-border-hover/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/border-white\/20/border-border-focus/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/text-white/text-text-primary/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/text-gray-400/text-text-secondary/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/text-gray-500/text-text-muted/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/bg-white\/5/bg-border/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/bg-white\/10/bg-border-hover/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/bg-white\/20/bg-border-focus/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/hover:bg-white\/5/hover:bg-border/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/hover:bg-white\/10/hover:bg-border-hover/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/hover:border-white\/10/hover:border-border-hover/g'
find src -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i -e 's/focus:border-white\/20/focus:border-border-focus/g'
