import "dotenv/config"; import express from "express"; import type { Pool } from "pg"; import { z } from "zod"; import { CoreError, recordDecision, seedLocationB, createBudgetLoop, resolveLoop } from "./core.js"; import { IngressService } from "./ingress/service.js"; import { providerRegistry } from "./ingress/provider-registry.js"; import { GoogleAuthorizationFlow, GoogleCommunicationIngressAdapter, GoogleScheduleIngressAdapter, GoogleTokenProvider } from "./ingress/google.js"; import { isOpaqueSecretReference, localDevelopmentSecretStore } from "./secrets/store.js"; import { InterpretationService } from "./interpretation/service.js"; import { ControlledModelEgressPolicy, DeterministicInterpretationProvider } from "./interpretation/provider.js";
export const createDirectorApp = (pool: Pool) => {
const app=express(); app.disable("x-powered-by"); app.use((q,r,n)=>{const origin=q.header("origin");const allowed=process.env.DIRECTOR_FRONTEND_ORIGIN??"http://127.0.0.1:3000";if(origin===allowed)r.setHeader("Access-Control-Allow-Origin",allowed);if(q.method==="OPTIONS"){r.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");r.setHeader("Access-Control-Allow-Headers","content-type");return r.sendStatus(204)}n();}); app.use(express.json({limit:"64kb"}));
const safe=(handler:any)=>(request:any,response:any,next:any)=>Promise.resolve(handler(request,response,next)).catch(next);
const active="('OPEN','IN_PROGRESS','WAITING','BLOCKED')";
const secretStore=localDevelopmentSecretStore(); const googleTokens=new GoogleTokenProvider(secretStore); const googleAuthorization=new GoogleAuthorizationFlow(); let ingress:IngressService;
const googleCommunication=new GoogleCommunicationIngressAdapter(googleTokens,id=>ingress.getConnection(id)); const googleSchedule=new GoogleScheduleIngressAdapter(googleTokens,id=>ingress.getConnection(id));
ingress=new IngressService(pool,{communication:new Map([["GOOGLE",googleCommunication]]),schedule:new Map([["GOOGLE",googleSchedule]])});
const interpretations=new InterpretationService(pool,new DeterministicInterpretationProvider(),new ControlledModelEgressPolicy());
async function attention(){const {rows}=await pool.query(`select o.*,d.id decision_id,d.status decision_status,ir.source_record_id from director_obligations o left join director_decisions d on d.obligation_id=o.id left join director_interpretation_candidates ic on ic.id=(o.provenance->>'interpretation_candidate_id')::uuid left join director_interpretation_runs ir on ir.id=ic.run_id where o.status in ${active} and o.kind in ('DECISION_REQUIRED','ACTION_REQUIRED') and (d.id is null or d.status='OPEN')`);return rows.map(x=>({id:x.decision_id??x.id,title:x.summary.toUpperCase(),classification:x.kind==='DECISION_REQUIRED'?"DECISION_REQUIRED":"ACTION_REQUIRED",deadline:x.due_at,project:x.project_ref,person:x.person_ref,status:"needs_you",trace:{interpretationCandidateId:x.provenance?.interpretation_candidate_id,sourceRecordId:x.source_record_id},rationale:[x.kind==='DECISION_REQUIRED'?"validated decision request":"validated action request","obligation is open",...(x.due_at?["deadline exists"]:[])]}));}
app.get("/health",(_,r)=>r.json({status:"ok",service:"ne-director-core"}));
app.get("/api/v1/attention",safe(async(_,r)=>r.json({kind:"projection",items:await attention()})));
app.get("/api/v1/today",safe(async(_:any,r:any)=>{const a=await attention();const loops=(await pool.query("select * from director_open_loops where status in ('OPEN','WAITING')")).rows; const timeline=(await pool.query("select * from director_timeline order by occurred_at desc")).rows; const calendar=await ingress.todaySchedule(); r.json({kind:"projection",needsYou:a,waitingFor:loops,calendar,handled:timeline.filter(x=>x.event_type==='DIRECTOR_DECISION_RECORDED'),timeline});}));
app.get("/api/v1/projects/:id",safe(async(q,r)=>{const a=await attention();const items=a.filter(x=>x.project.external_id===q.params.id.toLowerCase());r.json({kind:"projection",id:q.params.id,name:q.params.id.toUpperCase(),needsYouCount:items.length,openDecisions:items.length});}));
app.get("/api/v1/projects",safe(async(_,r)=>r.json({kind:"projection",items:[await (async()=>{const a=await attention();return {id:"harbour",name:"HARBOUR",needsYouCount:a.filter(x=>x.project.external_id==='harbour').length};})()]})));
app.get("/api/v1/people/:id",safe(async(q,r)=>{const a=await attention();const items=a.filter(x=>x.person?.external_id===q.params.id.toLowerCase());r.json({kind:"projection",id:q.params.id,name:q.params.id==="anna"?"Anna Meyer":q.params.id,openItemsCount:items.length,items});}));
app.get("/api/v1/people",safe(async(_,r)=>r.json({kind:"projection",items:[await (async()=>{const a=await attention();return {id:"anna",name:"Anna Meyer",openItemsCount:a.filter(x=>x.person?.external_id==='anna-meyer').length};})()]})));
app.get("/api/v1/timeline",safe(async(_,r)=>r.json({kind:"projection",items:(await pool.query("select * from director_timeline order by occurred_at desc")).rows})));
const connectionInput=z.object({displayName:z.string().min(1),provider:z.string().min(1),accountIdentifier:z.string().min(1),enabled:z.boolean().default(true),capabilities:z.array(z.enum(['MAIL','CALENDAR','CONTACTS'])).min(1).max(3).refine(values=>new Set(values).size===values.length),configurationMetadata:z.record(z.string(),z.unknown()).default({}),selectionMetadata:z.record(z.string(),z.unknown()).default({})});
const connectionPatch=z.object({displayName:z.string().min(1).optional(),enabled:z.boolean().optional(),capabilities:z.array(z.enum(['MAIL','CALENDAR','CONTACTS'])).min(1).max(3).refine(values=>new Set(values).size===values.length).optional(),configurationMetadata:z.record(z.string(),z.unknown()).optional()});
const sourceAccountPatch=z.object({displayName:z.string().min(1).optional(),enabled:z.boolean().optional(),selectionMetadata:z.record(z.string(),z.unknown()).optional()});
app.get("/api/v1/ingress/providers",(_,r)=>r.json({kind:"projection",items:providerRegistry}));
app.get("/api/v1/ingress/connections",safe(async(_,r)=>r.json({kind:"projection",items:await ingress.listConnections()})));
app.post("/api/v1/ingress/connections",safe(async(q,r)=>{const body=connectionInput.safeParse(q.body);if(!body.success)throw new CoreError("VALIDATION_ERROR",400,"Invalid connection configuration");const connection=await ingress.createConnection(body.data);const sourceAccounts=await Promise.all(body.data.capabilities.map(capability=>ingress.addConnectionCapability(connection.id,capability,body.data.selectionMetadata)));r.status(201).json({kind:"domain",connection:await ingress.getConnection(connection.id),sourceAccounts});}));
app.patch("/api/v1/ingress/connections/:id",safe(async(q,r)=>{const body=connectionPatch.safeParse(q.body);if(!body.success)throw new CoreError("VALIDATION_ERROR",400,"Invalid connection update");const connection=await ingress.updateConnection(q.params.id,body.data);const sourceAccounts=body.data.capabilities?await Promise.all(body.data.capabilities.map(capability=>ingress.addConnectionCapability(connection.id,capability))):undefined;r.json({kind:"domain",connection:await ingress.getConnection(connection.id),sourceAccounts});}));
app.post("/api/v1/ingress/connections/:id/authorization-intent",safe(async(q,r)=>{const connection=await ingress.getConnection(q.params.id);if(connection.provider!=="GOOGLE")throw new CoreError("PROVIDER_ADAPTER_NOT_IMPLEMENTED",409,"Provider authorization is not implemented");const handoff=googleAuthorization.begin(connection);r.json({kind:"domain",connection:await ingress.beginAuthorization(connection.id),authorizationUrl:handoff.authorizationUrl});}));
app.get("/api/v1/ingress/google/callback",safe(async(q,r)=>{const state=z.string().min(1).safeParse(q.query.state);const code=z.string().min(1).safeParse(q.query.code);if(!state.success||!code.success)throw new CoreError("GOOGLE_AUTH_CALLBACK_REJECTED",400,"Google authorization callback rejected");const completed=await googleAuthorization.complete(state.data,code.data);let reference:string|undefined;try{reference=await secretStore.put(completed.refreshToken,{ownerConnectionId:completed.connectionId,purpose:"OAUTH_REFRESH_TOKEN",provider:"GOOGLE",classification:"LOCAL_DEVELOPMENT_ONLY"});await ingress.setConnectionSecretReference(completed.connectionId,"googleRefreshTokenSecretRef",reference);await ingress.confirmAuthorization(completed.connectionId);}catch(error){if(reference)await secretStore.delete(reference).catch(()=>undefined);if(error instanceof CoreError)throw error;throw new CoreError("GOOGLE_SECRET_AUTHORITY_REQUIRED",503,"A local secret authority must store the Google refresh token");}r.status(204).send();}));
app.post("/api/v1/ingress/connections/:id/revoke",safe(async(q,r)=>{const existing=await ingress.getConnection(q.params.id);const reference=existing.configurationMetadata.googleRefreshTokenSecretRef;const connection=await ingress.revokeConnection(q.params.id);let localCredentialDisposition="NONE";if(isOpaqueSecretReference(reference)){try{if(reference.startsWith("secret://")){await secretStore.delete(reference);localCredentialDisposition="DELETED";}else localCredentialDisposition="ENVIRONMENT_REFERENCE_INVALIDATED";}catch{localCredentialDisposition="DELETE_FAILED_REFERENCE_INVALIDATED";}finally{await ingress.removeConnectionSecretReference(connection.id,"googleRefreshTokenSecretRef");}}r.json({kind:"domain",connection:await ingress.getConnection(connection.id),revocation:"LOCAL_REVOCATION_ONLY",localCredentialDisposition});}));
app.get("/api/v1/ingress/accounts",safe(async(_,r)=>r.json({kind:"projection",items:await ingress.listAccounts()})));
app.patch("/api/v1/ingress/accounts/:id",safe(async(q,r)=>{const body=sourceAccountPatch.safeParse(q.body);if(!body.success)throw new CoreError("VALIDATION_ERROR",400,"Invalid source account update");r.json({kind:"domain",sourceAccount:await ingress.updateSourceAccount(q.params.id,body.data)});}));
app.get("/api/v1/ingress/communications",safe(async(q,r)=>{const limit=Math.min(Number(q.query.limit??50),100),offset=Math.max(Number(q.query.offset??0),0);r.json({kind:"projection",items:await ingress.listCommunications(limit,offset),limit,offset});}));
app.get("/api/v1/ingress/schedule",safe(async(q,r)=>{const limit=Math.min(Number(q.query.limit??50),100),offset=Math.max(Number(q.query.offset??0),0);r.json({kind:"projection",items:await ingress.listSchedule(limit,offset),limit,offset});}));
app.post("/api/v1/ingress/sync",safe(async(q,r)=>{const body=z.object({sourceAccountId:z.string().uuid()}).safeParse(q.body);if(!body.success)throw new CoreError("VALIDATION_ERROR",400,"Invalid ingress sync command");r.json({kind:"projection",sync:await ingress.sync(body.data.sourceAccountId)});}));
app.post("/api/v1/interpretations",safe(async(q,r)=>{const body=z.object({sourceRecordId:z.string().uuid()}).safeParse(q.body);if(!body.success)throw new CoreError("VALIDATION_ERROR",400,"Invalid interpretation command");r.status(201).json({kind:"interpretation",run:await interpretations.interpret(body.data.sourceRecordId)});}));
app.get("/api/v1/interpretations",safe(async(q,r)=>{const sourceRecordId=z.string().uuid().optional().safeParse(q.query.sourceRecordId);if(!sourceRecordId.success)throw new CoreError("VALIDATION_ERROR",400,"Invalid source record filter");r.json({kind:"projection",items:await interpretations.list(sourceRecordId.data)});}));
app.get("/api/v1/interpretations/:id",safe(async(q,r)=>r.json({kind:"interpretation",run:await interpretations.getRun(q.params.id)})));
app.post("/api/v1/interpretations/:id/materialize",safe(async(q,r)=>r.json({kind:"materialization",result:await interpretations.materialize(q.params.id)})));
app.get("/api/v1/open-loops",safe(async(_,r)=>r.json({kind:"domain",items:(await pool.query("select * from director_open_loops where status in ('OPEN','WAITING') order by opened_at desc")).rows})));
app.get("/api/v1/open-loops/:id",safe(async(q,r)=>{const x=await pool.query("select * from director_open_loops where id=$1",[q.params.id]);if(!x.rowCount)throw new CoreError("NOT_FOUND",404,"Open loop not found");r.json({kind:"domain",openLoop:x.rows[0]});}));
app.post("/api/v1/open-loops/:id/resolve",safe(async(q,r)=>r.json({kind:"domain",id:await resolveLoop(pool,q.params.id),status:"RESOLVED"})));
app.get("/api/v1/decisions/:id",safe(async(q,r)=>{const x=await pool.query("select * from director_decisions where id=$1",[q.params.id]);if(!x.rowCount)throw new CoreError("NOT_FOUND",404,"Decision not found");r.json({kind:"domain",decision:x.rows[0]});}));
app.post("/api/v1/decisions/:id/record",safe(async(q,r)=>{const body=z.object({selectedOption:z.string().min(1),decidedBy:z.object({id:z.string().min(1),displayName:z.string().min(1)}).optional()}).safeParse(q.body);if(!body.success)throw new CoreError("VALIDATION_ERROR",400,"Invalid decision command");r.json({kind:"domain",decision:await recordDecision(pool,q.params.id,body.data.selectedOption,body.data.decidedBy)}); }));
if(process.env.NODE_ENV!=="production"){app.post("/api/v1/dev/fixtures/location-b",safe(async(_,r)=>r.status(201).json({decisionId:await seedLocationB(pool)})));app.post("/api/v1/dev/fixtures/budget-loop",safe(async(_,r)=>r.status(201).json({openLoopId:await createBudgetLoop(pool)})));}
app.use((e:any,_:any,r:any,_n:any)=>{const unavailable=e?.code==='ECONNREFUSED'||e?.code==='57P01';const x=e instanceof CoreError?e:new CoreError(unavailable?"PERSISTENCE_UNAVAILABLE":"PERSISTENCE_FAILURE",unavailable?503:500,unavailable?"Persistence unavailable":"Persistence failure");console.error(JSON.stringify({event:"core_error",code:x.code}));r.status(x.status).json({kind:"failure",code:x.code,message:x.message});});
return app;
};
if(import.meta.url===new URL(`file://${process.argv[1]}`).href) { const { pool } = await import("./persistence/db.js"); createDirectorApp(pool).listen(Number(process.env.DIRECTOR_PORT??4600),"127.0.0.1"); }
