import "dotenv/config"; import express from "express"; import { z } from "zod"; import { pool } from "./persistence/db.js"; import { CoreError, recordDecision, seedLocationB, createBudgetLoop, resolveLoop } from "./core.js";
const app=express(); app.disable("x-powered-by"); app.use(express.json({limit:"64kb"}));
const safe=(handler:any)=>(request:any,response:any,next:any)=>Promise.resolve(handler(request,response,next)).catch(next);
const active="('OPEN','IN_PROGRESS','WAITING','BLOCKED')";
async function attention(){const {rows}=await pool.query(`select o.*,d.id decision_id,d.options from director_obligations o join director_decisions d on d.obligation_id=o.id where o.status in ${active} and d.status='OPEN'`);return rows.map(x=>({id:x.decision_id,title:x.summary.toUpperCase(),classification:"DECISION_REQUIRED",deadline:x.due_at,project:x.project_ref,person:x.person_ref,status:"needs_you",rationale:["obligation type requires director decision","obligation is open",...(x.due_at?["deadline exists"]:[])]}));}
app.get("/health",(_,r)=>r.json({status:"ok",service:"ne-director-core"}));
app.get("/api/v1/attention",async(_,r)=>r.json({kind:"projection",items:await attention()}));
app.get("/api/v1/today",safe(async(_:any,r:any)=>{const a=await attention();const loops=(await pool.query("select * from director_open_loops where status in ('OPEN','WAITING')")).rows; const timeline=(await pool.query("select * from director_timeline order by occurred_at desc")).rows; r.json({kind:"projection",needsYou:a,waitingFor:loops,handled:timeline.filter(x=>x.event_type==='DIRECTOR_DECISION_RECORDED'),timeline});}));
app.get("/api/v1/projects/:id",async(q,r)=>{const a=await attention();const items=a.filter(x=>x.project.external_id===q.params.id.toLowerCase());r.json({kind:"projection",id:q.params.id,name:q.params.id.toUpperCase(),needsYouCount:items.length,openDecisions:items.length});});
app.get("/api/v1/projects",async(_,r)=>r.json({kind:"projection",items:[await (async()=>{const a=await attention();return {id:"harbour",name:"HARBOUR",needsYouCount:a.filter(x=>x.project.external_id==='harbour').length};})()]}));
app.get("/api/v1/people/:id",async(q,r)=>{const a=await attention();const items=a.filter(x=>x.person?.external_id===q.params.id.toLowerCase());r.json({kind:"projection",id:q.params.id,name:q.params.id==="anna"?"Anna Meyer":q.params.id,openItemsCount:items.length,items});});
app.get("/api/v1/people",async(_,r)=>r.json({kind:"projection",items:[await (async()=>{const a=await attention();return {id:"anna",name:"Anna Meyer",openItemsCount:a.filter(x=>x.person?.external_id==='anna-meyer').length};})()]}));
app.get("/api/v1/timeline",async(_,r)=>r.json({kind:"projection",items:(await pool.query("select * from director_timeline order by occurred_at desc")).rows}));
app.get("/api/v1/open-loops",async(_,r)=>r.json({kind:"domain",items:(await pool.query("select * from director_open_loops where status in ('OPEN','WAITING') order by opened_at desc")).rows}));
app.get("/api/v1/open-loops/:id",async(q,r)=>{const x=await pool.query("select * from director_open_loops where id=$1",[q.params.id]);if(!x.rowCount)throw new CoreError("NOT_FOUND",404,"Open loop not found");r.json({kind:"domain",openLoop:x.rows[0]});});
app.post("/api/v1/open-loops/:id/resolve",async(q,r)=>r.json({kind:"domain",id:await resolveLoop(pool,q.params.id),status:"RESOLVED"}));
app.get("/api/v1/decisions/:id",async(q,r)=>{const x=await pool.query("select * from director_decisions where id=$1",[q.params.id]);if(!x.rowCount)throw new CoreError("NOT_FOUND",404,"Decision not found");r.json({kind:"domain",decision:x.rows[0]});});
app.post("/api/v1/decisions/:id/record",async(q,r)=>{const body=z.object({selectedOption:z.enum(["LOCATION_A","LOCATION_B"]),decidedBy:z.object({id:z.string().min(1),displayName:z.string().min(1)}).optional()}).safeParse(q.body);if(!body.success)throw new CoreError("VALIDATION_ERROR",400,"Invalid decision command");r.json({kind:"domain",decision:await recordDecision(pool,q.params.id,body.data.selectedOption,body.data.decidedBy)});});
if(process.env.NODE_ENV!=="production"){app.post("/api/v1/dev/fixtures/location-b",async(_,r)=>r.status(201).json({decisionId:await seedLocationB(pool)}));app.post("/api/v1/dev/fixtures/budget-loop",async(_,r)=>r.status(201).json({openLoopId:await createBudgetLoop(pool)}));}
app.use((e:any,_:any,r:any,_n:any)=>{const unavailable=e?.code==='ECONNREFUSED'||e?.code==='57P01';const x=e instanceof CoreError?e:new CoreError(unavailable?"PERSISTENCE_UNAVAILABLE":"PERSISTENCE_FAILURE",unavailable?503:500,unavailable?"Persistence unavailable":"Persistence failure");console.error(JSON.stringify({event:"core_error",code:x.code}));r.status(x.status).json({kind:"failure",code:x.code,message:x.message});});
if(import.meta.url===new URL(`file://${process.argv[1]}`).href) app.listen(Number(process.env.DIRECTOR_PORT??4600),"127.0.0.1"); export {app};
