export type AgentId = 'CHIEF_OF_STAFF' | 'CALENDAR_TRAVEL' | 'COMMUNICATION' | 'PROJECT_DOCUMENT' | 'PRODUCTION_LIAISON' | 'RESEARCH' | 'PERSONAL_LOGISTICS';
export type Permission = 'SUGGEST_ONLY' | 'APPROVAL_REQUIRED' | 'ALLOWED';
export type SourceAccess = 'NONE' | 'CONTEXT_ONLY' | 'READ';
export interface OperatorControls { globalAutonomy: Record<string, Permission>; chiefOfStaff: { proactivity: 'QUIET' | 'BALANCED' | 'PROACTIVE'; dailyBrief: boolean; dailyBriefTime: string; endOfDayReview: boolean; endOfDayReviewTime: string; autoMeetingPrep: boolean; meetingPrepMinutes: number; followUpThresholdHours: number; }; globalPause: boolean; version: number; updatedAt?: string; }
export interface AgentRuntimeHealth { state: 'DISABLED' | 'PAUSED' | 'READY' | 'RUNNING' | 'DEGRADED'; enabled: boolean; globalPause: boolean; queued: number; running: number; blocked_policy: number; blocked_capability: number; completed_today: number; failed_today: number; oldest_queued: string | null; last_completed_at: string | null; lastTickAt: string | null; }
export interface AgentProjection { charter: { agentId: AgentId; displayName: string; shortDescription: string; purpose: string; responsibilities: string[]; exclusions: string[]; escalationRules: string[]; cannotDisable: boolean; sourceScopes: Record<string, SourceAccess>; }; operatorPolicy: { status: 'ACTIVE' | 'PAUSED'; delegationMode: 'MANUAL_ONLY' | 'AUTOMATIC_WHEN_ALLOWED'; modelStrategy: 'AUTOMATIC' | 'LOCAL_ONLY' | 'PRIVATE_ONLY' | 'HIGHEST_QUALITY'; capabilityOverrides: Record<string, Permission>; sourceScopeOverrides: Record<string, SourceAccess>; version: number; }; sourceAccess: Record<string, SourceAccess>; requestedSourceAccess: Record<string, SourceAccess>; derivedState: string; globalPause: boolean; capabilities: Array<{ capabilityId: string; actionClass: string; riskClass: string; globalAutonomyKey?: string; availability: string; effectiveState: string; effectiveAutonomy: Permission; operatorOverride?: Permission; limitingReason?: string; }>; effectiveCapabilitySummary: { available: number; limited: number; }; runtimeAuthority: 'INTERNAL_READ_PREPARATION_ONLY'; }
const base = import.meta.env.VITE_DIRECTOR_API_BASE_URL ?? 'http://127.0.0.1:4600/api/v1';
export const agentControlApiEnabled = import.meta.env.VITE_DIRECTOR_RUNTIME_MODE === 'api';
const request = async (path: string, options?: RequestInit) => { const response = await fetch(`${base}${path}`, { ...options, headers: { 'content-type': 'application/json', ...(options?.headers ?? {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.code ?? `Director API ${response.status}`); return body; };
export const agentControlApi = {
  async controls(): Promise<OperatorControls> { return (await request('/operator-controls')).controls; },
  async updateControls(input: Partial<OperatorControls> & { version: number }): Promise<OperatorControls> { return (await request('/operator-controls', { method: 'PATCH', body: JSON.stringify(input) })).controls; },
  async agents(): Promise<AgentProjection[]> { return (await request('/agents')).items; },
  async agent(agentId: AgentId): Promise<AgentProjection> { return (await request(`/agents/${agentId}`)).agent; },
  async updatePolicy(agentId: AgentId, input: { version: number; status?: 'ACTIVE' | 'PAUSED'; delegationMode?: 'MANUAL_ONLY' | 'AUTOMATIC_WHEN_ALLOWED'; modelStrategy?: 'AUTOMATIC' | 'LOCAL_ONLY' | 'PRIVATE_ONLY' | 'HIGHEST_QUALITY'; capabilityOverrides?: Record<string, Permission | null>; sourceScopeOverrides?: Record<string, SourceAccess | null> }): Promise<AgentProjection> { return (await request(`/agents/${agentId}/operator-policy`, { method: 'PATCH', body: JSON.stringify(input) })).agent; },
  async runtimeHealth(): Promise<AgentRuntimeHealth> { return (await request('/agent-runtime/health')).runtime; },
  async events() { return (await request('/agent-policy-events')).items; }
};
