import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { AgentOperatorControlService } from '../agents/service.js';
import { CoreError } from '../core.js';
import { migrateDatabase } from '../persistence/migration-runner.js';
import { createProofPool } from '../persistence/proof-db.js';
import { createDirectorApp } from '../server.js';

const pool = createProofPool();
await migrateDatabase(pool);
await pool.query('truncate director_agent_policy_events, director_agent_source_scope_overrides, director_agent_capability_overrides, director_agent_operator_policies, director_operator_controls');
await pool.query("delete from director_source_accounts where account_identifier like 'agent-control-proof:%'");
const service = new AgentOperatorControlService(pool);
const initial = await service.listAgents();
assert.equal(initial.length, 7);
assert.deepEqual(initial.map(agent => agent.charter.agentId), ['CHIEF_OF_STAFF', 'CALENDAR_TRAVEL', 'COMMUNICATION', 'PROJECT_DOCUMENT', 'PRODUCTION_LIAISON', 'RESEARCH', 'PERSONAL_LOGISTICS']);
assert.equal(initial.find(agent => agent.charter.agentId === 'COMMUNICATION')!.capabilities.find(capability => capability.capabilityId === 'COMMUNICATION_INTERPRET')!.availability, 'QUALITY_BLOCKED');
assert.equal(initial.find(agent => agent.charter.agentId === 'PRODUCTION_LIAISON')!.capabilities.find(capability => capability.capabilityId === 'ORDO_READ')!.availability, 'NOT_IMPLEMENTED');
assert.equal(initial.find(agent => agent.charter.agentId === 'COMMUNICATION')!.capabilities.find(capability => capability.capabilityId === 'MAIL_READ')!.availability, 'NOT_CONNECTED');
assert.equal(initial.find(agent => agent.charter.agentId === 'COMMUNICATION')!.sourceAccess.MAIL, 'NONE');
const controls = await service.getControls();
const capped = await service.updateControls({ version: controls.version, globalAutonomy: { sendExternalReplies: 'SUGGEST_ONLY' } });
const communicationBeforeEscalation = await service.getAgent('COMMUNICATION');
await assert.rejects(() => service.updateAgentPolicy('COMMUNICATION', { version: communicationBeforeEscalation.operatorPolicy.version, capabilityOverrides: { MAIL_SEND_EXTERNAL: 'ALLOWED' } }), (error: unknown) => error instanceof CoreError && error.code === 'AGENT_POLICY_CANNOT_ESCALATE');
const communication = await service.getAgent('COMMUNICATION');
const paused = await service.updateAgentPolicy('COMMUNICATION', { version: communication.operatorPolicy.version, status: 'PAUSED' });
assert.equal(paused.operatorPolicy.status, 'PAUSED');
assert.equal((await new AgentOperatorControlService(pool).getAgent('COMMUNICATION')).operatorPolicy.status, 'PAUSED');
const chief = await service.getAgent('CHIEF_OF_STAFF');
await assert.rejects(() => service.updateAgentPolicy('CHIEF_OF_STAFF', { version: chief.operatorPolicy.version, status: 'PAUSED' }), (error: unknown) => error instanceof CoreError && error.code === 'CHIEF_OF_STAFF_CANNOT_DISABLE');
const resumed = await service.updateAgentPolicy('COMMUNICATION', { version: paused.operatorPolicy.version, status: 'ACTIVE' });
assert.equal(resumed.operatorPolicy.status, 'ACTIVE');
const research = await service.getAgent('RESEARCH');
await service.updateAgentPolicy('RESEARCH', { version: research.operatorPolicy.version, sourceScopeOverrides: { PROJECT: 'NONE' } });
const restrictedResearch = await service.getAgent('RESEARCH');
await assert.rejects(() => service.updateAgentPolicy('RESEARCH', { version: restrictedResearch.operatorPolicy.version, sourceScopeOverrides: { PROJECT: 'READ' } }), (error: unknown) => error instanceof CoreError && error.code === 'AGENT_SOURCE_CANNOT_ESCALATE');
await pool.query("insert into director_source_accounts(id,provider,capability,display_name,account_identifier,enabled,connection_state) values($1,'GOOGLE','COMMUNICATION','Agent proof mail',$2,true,'CONNECTED'),($3,'GOOGLE','SCHEDULE','Agent proof calendar',$4,true,'CONNECTED')", [randomUUID(), 'agent-control-proof:mail', randomUUID(), 'agent-control-proof:calendar']);
const connected = await service.listAgents();
assert.equal(connected.find(agent => agent.charter.agentId === 'COMMUNICATION')!.capabilities.find(capability => capability.capabilityId === 'MAIL_READ')!.availability, 'AVAILABLE');
assert.equal(connected.find(agent => agent.charter.agentId === 'COMMUNICATION')!.sourceAccess.MAIL, 'READ');
assert.equal(connected.find(agent => agent.charter.agentId === 'CALENDAR_TRAVEL')!.capabilities.find(capability => capability.capabilityId === 'CALENDAR_READ')!.availability, 'AVAILABLE');
const beforePause = await service.getControls();
const globallyPaused = await service.updateControls({ version: beforePause.version, globalPause: true });
assert.equal((await service.listAgents()).every(agent => agent.derivedState === 'OPERATOR_PAUSED'), true);
const restored = await service.updateControls({ version: globallyPaused.version, globalPause: false });
assert.equal((await service.getAgent('COMMUNICATION')).operatorPolicy.status, 'ACTIVE');
await assert.rejects(() => service.updateControls({ version: capped.version, globalPause: true }), (error: unknown) => error instanceof CoreError && error.code === 'STALE_POLICY_VERSION');
assert.equal((await service.events()).length >= 6, true);
assert.equal(restored.globalPause, false);
const app = createDirectorApp(pool); const http = app.listen(0, '127.0.0.1');
await new Promise<void>(resolve => http.once('listening', resolve));
const address = http.address(); if (!address || typeof address === 'string') throw new Error('API proof listener unavailable');
const base = `http://127.0.0.1:${address.port}/api/v1`;
const apiAgents = await (await fetch(`${base}/agents`)).json() as any;
assert.equal(apiAgents.items.length, 7);
const apiCommunication = await (await fetch(`${base}/agents/COMMUNICATION`)).json() as any;
assert.equal(apiCommunication.agent.capabilities.find((capability: any) => capability.capabilityId === 'COMMUNICATION_INTERPRET').availability, 'QUALITY_BLOCKED');
const rejectedChief = await fetch(`${base}/agents/CHIEF_OF_STAFF/operator-policy`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ version: (await service.getAgent('CHIEF_OF_STAFF')).operatorPolicy.version, status: 'PAUSED' }) });
assert.equal(rejectedChief.status, 422);
await new Promise<void>((resolve, reject) => http.close(error => error ? reject(error) : resolve()));
console.log(JSON.stringify({ agents: initial.length, api: true, qualityBlocked: true, connectionAware: true, pauseRestore: true, staleRejected: true, auditEvents: (await service.events()).length, runtimeAuthority: 'INTERNAL_READ_PREPARATION_ONLY', noExternalMutation: true }));
await pool.end();
