import { createHash, randomUUID } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import { CoreError } from '../core.js';
import { AgentOperatorControlService } from '../agents/service.js';
import { runtimeWorkRegistry, type RuntimeClock, SystemRuntimeClock, type WorkType } from './contracts.js';

const json = (value: unknown) => JSON.stringify(value);
const hash = (value: unknown) => createHash('sha256').update(JSON.stringify(value)).digest('hex');
const local = (date: Date) => new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/Berlin', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(date).reduce((result, part) => ({ ...result, [part.type]: part.value }), {} as Record<string, string>);
const dayKey = (date: Date) => { const parts = local(date); return `${parts.year}-${parts.month}-${parts.day}`; };
const reached = (date: Date, time: string) => { const parts = local(date); return `${parts.hour}:${parts.minute}` >= time; };
const event = async (db: Pool | PoolClient, eventType: string, workId?: string, triggerId?: string, detail: Record<string, unknown> = {}) => db.query('insert into director_agent_runtime_events(id,work_item_id,trigger_occurrence_id,event_type,detail,provenance) values($1,$2,$3,$4,$5,$6)', [randomUUID(), workId ?? null, triggerId ?? null, eventType, json(detail), json({ authority: 'NE_DIRECTOR_AGENT_RUNTIME_DELEGATION_AND_TRIGGER_AUTHORITY_001', internal_only: true })]);

export class AgentRuntimeRunner {
  readonly controls: AgentOperatorControlService;
  constructor(private readonly db: Pool, private readonly clock: RuntimeClock = new SystemRuntimeClock(), private readonly workerId = `runtime-${process.pid}`, private readonly beforeResultCommit?: () => Promise<void>) { this.controls = new AgentOperatorControlService(db); }
  enabled() { return process.env.DIRECTOR_AGENT_RUNTIME_ENABLED === 'true'; }
  async health() { const controls = await this.controls.getControls(); const counts = await this.db.query("select count(*) filter(where status in ('QUEUED','WAITING_FOR_DELEGATION'))::int queued,count(*) filter(where status='RUNNING')::int running,count(*) filter(where status='BLOCKED_POLICY')::int blocked_policy,count(*) filter(where status='BLOCKED_CAPABILITY')::int blocked_capability,count(*) filter(where status='COMPLETED' and completed_at >= date_trunc('day',now()))::int completed_today,count(*) filter(where status='FAILED' and failed_at >= date_trunc('day',now()))::int failed_today,min(created_at) filter(where status='QUEUED') oldest_queued,max(completed_at) last_completed_at from director_agent_work_items"); const cursor = await this.db.query("select value from director_agent_runtime_cursors where key='last_tick'"); const lastTickAt = cursor.rows[0]?.value?.at ?? null; const age = lastTickAt ? Date.now() - new Date(lastTickAt).getTime() : undefined; const state = !this.enabled() ? 'DISABLED' : controls.globalPause ? 'PAUSED' : age === undefined ? 'READY' : age <= 90_000 ? 'RUNNING' : 'DEGRADED'; return { state, enabled: this.enabled(), globalPause: controls.globalPause, ...(counts.rows[0] ?? {}), lastTickAt }; }
  async tick(now = this.clock.now(), force = false) { if (!force && !this.enabled()) return { state: 'DISABLED', created: 0, completed: 0 }; await this.db.query("insert into director_agent_runtime_cursors(key,value) values('last_tick',$1) on conflict(key) do update set value=excluded.value,updated_at=now()", [json({ at: now.toISOString() })]); const controls = await this.controls.getControls(); if (controls.globalPause) return { state: 'PAUSED', created: 0, completed: 0 }; await this.resumeEligibleWork(); let created = 0; created += await this.meetingTriggers(now, controls.chiefOfStaff.autoMeetingPrep, controls.chiefOfStaff.meetingPrepMinutes); if (controls.chiefOfStaff.dailyBrief && reached(now, controls.chiefOfStaff.dailyBriefTime)) created += await this.scheduledTrigger('DAILY_BRIEF_DUE', 'DAILY_BRIEF', `daily:${dayKey(now)}`, now); if (controls.chiefOfStaff.endOfDayReview && reached(now, controls.chiefOfStaff.endOfDayReviewTime)) created += await this.scheduledTrigger('END_OF_DAY_REVIEW_DUE', 'END_OF_DAY_REVIEW', `eod:${dayKey(now)}`, now); const completed = await this.consume(now); return { state: 'RUNNING', created, completed }; }
  private async resumeEligibleWork() {
    const waiting = await this.db.query("select id, assigned_agent_id, trigger_occurrence_id from director_agent_work_items where status='WAITING_FOR_DELEGATION'");
    for (const work of waiting.rows) {
      const agent = await this.controls.getAgent(work.assigned_agent_id);
      if (agent.operatorPolicy.delegationMode !== 'MANUAL_ONLY') {
        await this.db.query("update director_agent_work_items set status='QUEUED',failure_code=null,blocked_at=null where id=$1 and status='WAITING_FOR_DELEGATION'", [work.id]);
        await event(this.db, 'WORK_DELEGATION_APPROVED_BY_POLICY', work.id, work.trigger_occurrence_id);
      }
    }
    const blocked = await this.db.query("update director_agent_work_items set status='QUEUED',failure_code=null,blocked_at=null where status in ('BLOCKED_POLICY','BLOCKED_CAPABILITY') returning id,trigger_occurrence_id");
    for (const work of blocked.rows) await event(this.db, 'WORK_REQUEUED_FOR_AUTHORITY_RECHECK', work.id, work.trigger_occurrence_id);
  }
  private async meetingTriggers(now: Date, enabled: boolean, minutes: number) { if (!enabled) return 0; const rows = await this.db.query("select s.* from director_schedule_source_records s where s.is_current=true and s.is_active=true and s.status not in ('CANCELLED','REMOVED') and s.starts_at >= $1 and s.starts_at <= $2", [now, new Date(now.getTime() + minutes * 60_000)]); let created = 0; for (const source of rows.rows) created += await this.createTrigger('MEETING_PREPARATION_DUE', 'MEETING_PREPARATION', `meeting:${source.id}:${source.provider_revision}`, { scheduleRecordId: source.id, providerRevision: source.provider_revision, sourceAccountId: source.source_account_id }, source.starts_at, now); return created; }
  private async scheduledTrigger(kind: string, workType: WorkType, key: string, now: Date) { return this.createTrigger(kind, workType, key, { operatorDay: dayKey(now) }, now, now); }
  private async createTrigger(kind: string, workType: WorkType, key: string, source: Record<string, unknown>, dueAt: Date, now: Date) { const client = await this.db.connect(); try { await client.query('begin'); const inserted = await client.query("insert into director_agent_trigger_occurrences(id,trigger_type,trigger_version,trigger_key,source_type,source_ref,source_revision,due_at,observed_at,status,provenance) values($1,$2,'1.0.0',$3,$4,$5,$6,$7,$8,'PENDING',$9) on conflict(trigger_key) do nothing returning id", [randomUUID(), kind, key, workType === 'MEETING_PREPARATION' ? 'SCHEDULE' : 'OPERATOR_POLICY', json(source), source.providerRevision ?? null, dueAt, now, json({ workType, authority: 'NE_DIRECTOR_AGENT_RUNTIME_DELEGATION_AND_TRIGGER_AUTHORITY_001' })]); if (!inserted.rowCount) { await client.query('commit'); return 0; } const triggerId = inserted.rows[0].id; await event(client, 'TRIGGER_CREATED', undefined, triggerId, { kind, key }); await this.createWork(client, triggerId, workType, key, source, now); await client.query('commit'); return 1; } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
  private async createWork(client: PoolClient, triggerId: string, workType: WorkType, key: string, source: Record<string, unknown>, now: Date) { const definition = runtimeWorkRegistry[workType]; const delegate = definition.allowedDelegates[0]; let status = 'QUEUED'; if (delegate) { const agent = await this.controls.getAgent(delegate); if (agent.operatorPolicy.delegationMode === 'MANUAL_ONLY') status = 'WAITING_FOR_DELEGATION'; }
    const id = randomUUID(); const inserted = await client.query('insert into director_agent_work_items(id,work_type,work_version,trigger_occurrence_id,owning_agent_id,assigned_agent_id,status,subject_type,subject_ref,idempotency_key,required_capabilities,max_attempts,policy_snapshot_hash,provenance,available_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) on conflict(idempotency_key) do nothing returning id', [id, workType, definition.workVersion, triggerId, definition.owningAgent, delegate ?? definition.owningAgent, status, source.scheduleRecordId ? 'SCHEDULE' : 'OPERATOR_DAY', json(source), `work:${key}`, json(definition.requiredCapabilities), definition.maxAttempts, hash({ workType, delegate, capabilities: definition.requiredCapabilities }), json({ sideEffectClass: 'INTERNAL_ONLY', triggerOccurrenceId: triggerId }), now]); if (!inserted.rowCount) return; await event(client, 'WORK_CREATED', id, triggerId, { workType, status }); if (delegate) { await client.query('insert into director_agent_delegations(id,work_item_id,delegating_agent_id,receiving_agent_id,reason,required_work_type,policy_decision,provenance) values($1,$2,$3,$4,$5,$6,$7,$8)', [randomUUID(), id, definition.owningAgent, delegate, 'Deterministic work registry delegate', workType, json({ status }), json({ internal_only: true })]); await event(client, 'WORK_DELEGATED', id, triggerId, { delegate, status }); } if (status === 'QUEUED') await event(client, 'WORK_QUEUED', id, triggerId); }
  private async consume(now: Date) { let completed = 0; for (;;) { const work = await this.claim(now); if (!work) return completed; const definition = runtimeWorkRegistry[work.work_type as WorkType]; try { await this.controls.authorizeAgentWork(work.assigned_agent_id, definition.requiredCapabilities); const result = await this.execute(work, now); await this.beforeResultCommit?.(); await this.controls.authorizeAgentWork(work.assigned_agent_id, definition.requiredCapabilities); await this.complete(work, result); completed++; } catch (error) { const code = error instanceof CoreError ? error.code : 'RUNTIME_TRANSIENT_FAILURE'; if (code === 'SCHEDULE_SUPERSEDED') await this.supersede(work, code); else if (code === 'RUNTIME_TRANSIENT_FAILURE' && work.attempt_count < work.max_attempts) await this.retry(work, now, code); else await this.block(work, code, code === 'AGENT_RUNTIME_CAPABILITY_BLOCKED' || code === 'QUALITY_BLOCKED' ? 'BLOCKED_CAPABILITY' : code === 'AGENT_RUNTIME_POLICY_BLOCKED' ? 'BLOCKED_POLICY' : 'FAILED'); } } }
  private async claim(now: Date) { const client = await this.db.connect(); try { await client.query('begin'); const result = await client.query("select * from director_agent_work_items where (status='QUEUED' or (status='RUNNING' and lease_expires_at < $1)) and available_at <= $1 order by created_at for update skip locked limit 1", [now]); if (!result.rowCount) { await client.query('commit'); return undefined; } const work = result.rows[0]; await client.query("update director_agent_work_items set status='RUNNING',lease_owner=$2,lease_expires_at=$3,started_at=coalesce(started_at,$1),attempt_count=attempt_count+1 where id=$4", [now, this.workerId, new Date(now.getTime() + 60_000), work.id]); await event(client, 'WORK_CLAIMED', work.id, work.trigger_occurrence_id, { worker: this.workerId }); await event(client, 'WORK_STARTED', work.id, work.trigger_occurrence_id); await client.query('commit'); return { ...work, attempt_count: work.attempt_count + 1 }; } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
  private async execute(work: any, now: Date) { if (work.work_type === 'MEETING_PREPARATION') { const row = await this.db.query("select s.*,a.display_name account_name from director_schedule_source_records s join director_source_accounts a on a.id=s.source_account_id where s.id=$1 and s.is_current=true and s.is_active=true and s.status not in ('CANCELLED','REMOVED')", [work.subject_ref.scheduleRecordId]); if (!row.rowCount) throw new CoreError('SCHEDULE_SUPERSEDED', 409, 'Current schedule revision is unavailable'); const meeting = row.rows[0]; const obligations = await this.db.query("select id,summary,due_at from director_obligations where status in ('OPEN','IN_PROGRESS','WAITING','BLOCKED') and (project_ref=$1 or person_ref=$2)", [meeting.provenance?.project_ref ?? {}, meeting.provenance?.person_ref ?? {}]); return { artifactType: 'MEETING_PREPARATION', content: { title: meeting.title, startsAt: meeting.starts_at, endsAt: meeting.ends_at, location: meeting.location ?? null, organizer: meeting.organizer ?? null, attendees: meeting.attendees ?? [], timeUntilMinutes: Math.max(0, Math.round((new Date(meeting.starts_at).getTime() - now.getTime()) / 60_000)), sourceAccount: meeting.account_name, scheduleRecordId: meeting.id, openObligations: obligations.rows, context: obligations.rowCount ? 'Canonical linked Director obligations included.' : 'Not enough context available.', externalActions: 'NONE' } }; }
    if (work.work_type === 'DAILY_BRIEF') { const [obligations, loops, calendar] = await Promise.all([this.db.query("select id,summary,due_at,status from director_obligations where status in ('OPEN','IN_PROGRESS','WAITING','BLOCKED') order by due_at nulls last limit 20"), this.db.query("select id,expected_result,expected_by,status from director_open_loops where status in ('OPEN','WAITING') limit 20"), this.db.query("select id,title,starts_at from director_schedule_source_records where is_current=true and is_active=true and starts_at >= $1 order by starts_at limit 10", [now])]); return { artifactType: 'DAILY_BRIEF', content: { facts: { openObligations: obligations.rows, openLoops: loops.rows, upcomingCalendar: calendar.rows }, externalActions: 'NONE' } }; }
    const [obligations, decisions, loops, tomorrow] = await Promise.all([this.db.query("select id,summary,due_at from director_obligations where status in ('OPEN','IN_PROGRESS','WAITING','BLOCKED')"), this.db.query("select id,question,required_by from director_decisions where status='OPEN'"), this.db.query("select id,expected_result,expected_by from director_open_loops where status in ('OPEN','WAITING')"), this.db.query("select id,title,starts_at from director_schedule_source_records where is_current=true and is_active=true and starts_at >= $1 and starts_at < $2 order by starts_at", [new Date(now.getTime() + 86400000), new Date(now.getTime() + 172800000)] )]); return { artifactType: 'END_OF_DAY_REVIEW', content: { unresolvedObligations: obligations.rows, openDecisions: decisions.rows, openLoops: loops.rows, tomorrowCalendar: tomorrow.rows, externalActions: 'NONE' } }; }
  private async complete(work: any, result: { artifactType: string; content: unknown }) { const client = await this.db.connect(); try { await client.query('begin'); const current = await client.query("select * from director_agent_work_items where id=$1 for update", [work.id]); if (!current.rowCount || current.rows[0].lease_owner !== this.workerId) throw new CoreError('WORK_LEASE_LOST', 409, 'Work lease lost'); if (work.work_type === 'MEETING_PREPARATION') { const source = await client.query("select id from director_schedule_source_records where id=$1 and provider_revision=$2 and is_current=true and is_active=true and status not in ('CANCELLED','REMOVED')", [work.subject_ref.scheduleRecordId, work.subject_ref.providerRevision]); if (!source.rowCount) throw new CoreError('SCHEDULE_SUPERSEDED', 409, 'Schedule changed before result commit'); } const artifactId = randomUUID(); await client.query('insert into director_agent_work_artifacts(id,work_item_id,artifact_type,artifact_version,structured_content,content_hash,provenance) values($1,$2,$3,$4,$5,$6,$7)', [artifactId, work.id, result.artifactType, '1.0.0', json(result.content), hash(result.content), json({ agentId: work.assigned_agent_id, workType: work.work_type, triggerOccurrenceId: work.trigger_occurrence_id, sourceRefs: work.subject_ref, executorId: 'DETERMINISTIC_INTERNAL_EXECUTOR', executorVersion: '1.0.0', externalActions: 'NONE' })]); await client.query("update director_agent_work_items set status='COMPLETED',completed_at=now(),lease_owner=null,lease_expires_at=null,result_artifact_id=$2 where id=$1", [work.id, artifactId]); await client.query("update director_agent_trigger_occurrences set status='CONSUMED' where id=$1", [work.trigger_occurrence_id]); await event(client, 'WORK_COMPLETED', work.id, work.trigger_occurrence_id, { artifactId }); await client.query('commit'); } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
  private async block(work: any, code: string, status: 'BLOCKED_POLICY' | 'BLOCKED_CAPABILITY' | 'FAILED') { const eventType = status === 'BLOCKED_POLICY' ? 'WORK_BLOCKED_POLICY' : status === 'BLOCKED_CAPABILITY' ? 'WORK_BLOCKED_CAPABILITY' : 'WORK_FAILED'; await this.db.query('update director_agent_work_items set status=$2,blocked_at=case when $2 like \'BLOCKED%\' then now() else blocked_at end,failed_at=case when $2=\'FAILED\' then now() else failed_at end,failure_code=$3,lease_owner=null,lease_expires_at=null where id=$1 and lease_owner=$4', [work.id, status, code, this.workerId]); await event(this.db, eventType, work.id, work.trigger_occurrence_id, { code }); }
  private async retry(work: any, now: Date, code: string) { const backoffMs = Math.min(60_000, 1_000 * 2 ** Math.max(0, work.attempt_count - 1)); await this.db.query("update director_agent_work_items set status='QUEUED',available_at=$2,failure_code=$3,lease_owner=null,lease_expires_at=null where id=$1 and lease_owner=$4", [work.id, new Date(now.getTime() + backoffMs), code, this.workerId]); await event(this.db, 'WORK_RETRY_SCHEDULED', work.id, work.trigger_occurrence_id, { code, backoffMs, attempt: work.attempt_count }); }
  private async supersede(work: any, code: string) { await this.db.query("update director_agent_work_items set status='SUPERSEDED',failure_code=$2,lease_owner=null,lease_expires_at=null where id=$1 and lease_owner=$3", [work.id, code, this.workerId]); await this.db.query("update director_agent_trigger_occurrences set status='SUPERSEDED' where id=$1", [work.trigger_occurrence_id]); await event(this.db, 'WORK_SUPERSEDED', work.id, work.trigger_occurrence_id, { code }); }
  async listWork() { return (await this.db.query('select * from director_agent_work_items order by created_at desc')).rows; }
  async getWork(id: string) { const result = await this.db.query('select * from director_agent_work_items where id=$1', [id]); if (!result.rowCount) throw new CoreError('NOT_FOUND', 404, 'Agent work not found'); return result.rows[0]; }
  async workEvents(id: string) { return (await this.db.query('select * from director_agent_runtime_events where work_item_id=$1 order by occurred_at', [id])).rows; }
  async artifact(id: string) { const result = await this.db.query('select * from director_agent_work_artifacts where id=$1', [id]); if (!result.rowCount) throw new CoreError('NOT_FOUND', 404, 'Agent work artifact not found'); return result.rows[0]; }
}
