export const agentIds = ['CHIEF_OF_STAFF', 'CALENDAR_TRAVEL', 'COMMUNICATION', 'PROJECT_DOCUMENT', 'PRODUCTION_LIAISON', 'RESEARCH', 'PERSONAL_LOGISTICS'] as const;
export type AgentId = typeof agentIds[number];
export type AutonomyPermission = 'SUGGEST_ONLY' | 'APPROVAL_REQUIRED' | 'ALLOWED';
export type AgentStatus = 'ACTIVE' | 'PAUSED';
export type DelegationMode = 'MANUAL_ONLY' | 'AUTOMATIC_WHEN_ALLOWED';
export type ModelStrategy = 'AUTOMATIC' | 'LOCAL_ONLY' | 'PRIVATE_ONLY' | 'HIGHEST_QUALITY';
export type SourceAccess = 'NONE' | 'CONTEXT_ONLY' | 'READ';
export type CapabilityAvailability = 'AVAILABLE' | 'NOT_CONNECTED' | 'NOT_IMPLEMENTED' | 'QUALITY_BLOCKED' | 'AUTHORITY_MISSING' | 'OPERATOR_PAUSED' | 'AGENT_PAUSED' | 'POLICY_BLOCKED' | 'DEGRADED';
export type ActionClass = 'READ' | 'INTERPRET' | 'PREPARE' | 'DRAFT' | 'MUTATE' | 'DELEGATE' | 'RESEARCH';
export type RiskClass = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type CapabilityId =
  | 'CALENDAR_READ' | 'CALENDAR_EVENT_CREATE_EXTERNAL' | 'CALENDAR_CREATE_INTERNAL_HOLD' | 'CALENDAR_MOVE_INTERNAL' | 'CALENDAR_MOVE_EXTERNAL' | 'CALENDAR_CANCEL' | 'TRAVEL_RESEARCH' | 'TRAVEL_BOOK'
  | 'MAIL_READ' | 'COMMUNICATION_INTERPRET' | 'MAIL_DRAFT_INTERNAL' | 'MAIL_SEND_INTERNAL' | 'MAIL_DRAFT_EXTERNAL' | 'MAIL_SEND_EXTERNAL' | 'FOLLOWUP_PREPARE' | 'FOLLOWUP_SEND'
  | 'PROJECT_READ' | 'DOCUMENT_READ' | 'DOCUMENT_REQUEST_MISSING' | 'DOCUMENT_DISTRIBUTE_APPROVED' | 'DOCUMENT_SHARE_CONFIDENTIAL' | 'NARRATE_READ' | 'MNEME_CONTEXT_READ'
  | 'ORDO_READ' | 'PRESENCE_READ' | 'NARRATE_CONTEXT_READ' | 'PRODUCTION_STATE_UPDATE' | 'PRODUCTION_DEPENDENCY_RESOLVE' | 'PRODUCTION_SCHEDULE_CHANGE'
  | 'WEB_RESEARCH' | 'IMPERIUM_MENTIS_READ' | 'PROJECT_CONTEXT_READ' | 'PERSONAL_CALENDAR_READ' | 'RESERVATION_PREPARE' | 'PERSONAL_MEMORY_READ';

export interface AgentCharter {
  agentId: AgentId; charterVersion: '1.0.0'; displayName: string; shortDescription: string; purpose: string;
  responsibilities: string[]; exclusions: string[]; declaredCapabilities: CapabilityId[]; sourceScopes: Record<string, SourceAccess>;
  escalationRules: string[]; defaultOperatorPolicy: { status: AgentStatus; delegationMode: DelegationMode; modelStrategy: ModelStrategy };
  modelPolicySupport: boolean; cannotDisable: boolean; provenance: { authority: 'NE_DIRECTOR_AGENT_CHARTER_CAPABILITY_AND_OPERATOR_CONTROL_AUTHORITY_001'; versionControlled: true };
}
export interface AgentCapabilityDefinition { capabilityId: CapabilityId; domain: string; actionClass: ActionClass; riskClass: RiskClass; requiredSystem: string; requiredAuthority: string; mutating: boolean; charterDeclared: true; globalAutonomyKey?: string; availabilityEvaluator: 'GOOGLE_MAIL' | 'GOOGLE_CALENDAR' | 'GOOGLE_CALENDAR_WRITE' | 'QUALITY_GATE' | 'NOT_IMPLEMENTED'; }

const provenance = { authority: 'NE_DIRECTOR_AGENT_CHARTER_CAPABILITY_AND_OPERATOR_CONTROL_AUTHORITY_001' as const, versionControlled: true as const };
const specialist = (agentId: AgentId, displayName: string, shortDescription: string, purpose: string, responsibilities: string[], exclusions: string[], declaredCapabilities: CapabilityId[], sourceScopes: Record<string, SourceAccess>): AgentCharter => ({ agentId, charterVersion: '1.0.0', displayName, shortDescription, purpose, responsibilities, exclusions, declaredCapabilities, sourceScopes, escalationRules: ['Escalate unsupported authority, ambiguity, and any external side effect to the operator.'], defaultOperatorPolicy: { status: agentId === 'PERSONAL_LOGISTICS' ? 'PAUSED' : 'ACTIVE', delegationMode: 'MANUAL_ONLY', modelStrategy: 'AUTOMATIC' }, modelPolicySupport: true, cannotDisable: false, provenance });

export const agentCharters: readonly AgentCharter[] = [
  { agentId: 'CHIEF_OF_STAFF', charterVersion: '1.0.0', displayName: 'Chief of Staff', shortDescription: 'Coordinates the specialist team and operator attention.', purpose: 'Primary orchestration and attention authority presented to the operator.', responsibilities: ['Coordinate specialist agents', 'Surface decisions, obligations, and open loops', 'Prepare Daily Brief, End of Day Review, and meeting context', 'Prioritize attention and recommend next actions'], exclusions: ['No direct external side effects', 'No bypass of specialist or global autonomy policy', 'No fabricated downstream outcome', 'No automatic real-source interpretation while model quality is blocked'], declaredCapabilities: [], sourceScopes: { MAIL: 'CONTEXT_ONLY', CALENDAR: 'CONTEXT_ONLY', PROJECT: 'CONTEXT_ONLY' }, escalationRules: ['Escalate all side effects and unsupported authority to the operator.'], defaultOperatorPolicy: { status: 'ACTIVE', delegationMode: 'MANUAL_ONLY', modelStrategy: 'AUTOMATIC' }, modelPolicySupport: true, cannotDisable: true, provenance },
  specialist('CALENDAR_TRAVEL', 'Calendar & Travel', 'Schedule awareness, coordination, and travel logistics.', 'Schedule awareness, calendar coordination and travel logistics.', ['Read authorized calendar facts', 'Identify conflicts and prepare meeting context', 'Prepare approval-bound calendar creation'], ['No unattended calendar mutation', 'No travel booking in this authority'], ['CALENDAR_READ', 'CALENDAR_EVENT_CREATE_EXTERNAL', 'CALENDAR_CREATE_INTERNAL_HOLD', 'CALENDAR_MOVE_INTERNAL', 'CALENDAR_MOVE_EXTERNAL', 'CALENDAR_CANCEL', 'TRAVEL_RESEARCH', 'TRAVEL_BOOK'], { CALENDAR: 'READ', TRAVEL: 'CONTEXT_ONLY' }),
  specialist('COMMUNICATION', 'Communication', 'Communication triage, interpretation, and follow-up preparation.', 'Communication triage, operational interpretation, reply preparation and follow-up tracking.', ['Read authorized communication facts', 'Triage requests, decisions, and expectations', 'Prepare reply and follow-up candidates later'], ['No real-source interpretation while quality is blocked', 'No draft or send action in this authority'], ['MAIL_READ', 'COMMUNICATION_INTERPRET', 'MAIL_DRAFT_INTERNAL', 'MAIL_SEND_INTERNAL', 'MAIL_DRAFT_EXTERNAL', 'MAIL_SEND_EXTERNAL', 'FOLLOWUP_PREPARE', 'FOLLOWUP_SEND'], { MAIL: 'READ', CALENDAR: 'CONTEXT_ONLY', CONTACTS: 'NONE' }),
  specialist('PROJECT_DOCUMENT', 'Project & Documents', 'Project and document awareness.', 'Maintain project/document awareness and prepare document-related work.', ['Track required documents and revisions', 'Surface missing material and prepare document context'], ['No claim of NARRATE or MNEME connectivity without integration'], ['PROJECT_READ', 'DOCUMENT_READ', 'DOCUMENT_REQUEST_MISSING', 'DOCUMENT_DISTRIBUTE_APPROVED', 'DOCUMENT_SHARE_CONFIDENTIAL', 'NARRATE_READ', 'MNEME_CONTEXT_READ'], { PROJECT: 'READ', DOCUMENT: 'READ', NARRATE: 'NONE', MNEME: 'NONE' }),
  specialist('PRODUCTION_LIAISON', 'Production Liaison', 'Production awareness and bounded coordination boundary.', 'Operational production awareness and coordination boundary between Director and production systems.', ['Monitor blockers, dependencies, and readiness', 'Prepare change-impact context and track waiting items'], ['Never infer ORDO or PRESENCE integration', 'No production mutation in this authority'], ['ORDO_READ', 'PRESENCE_READ', 'NARRATE_CONTEXT_READ', 'PRODUCTION_STATE_UPDATE', 'PRODUCTION_DEPENDENCY_RESOLVE', 'PRODUCTION_SCHEDULE_CHANGE'], { ORDO: 'NONE', PRESENCE: 'NONE', NARRATE: 'NONE' }),
  specialist('RESEARCH', 'Research', 'Decision-support research and context.', 'Prepare decision-support research and context.', ['Prepare person, company, meeting, topic, industry, and project context'], ['No outbound communication', 'No web runtime or IMPERIUM MENTIS delegation in this authority'], ['WEB_RESEARCH', 'IMPERIUM_MENTIS_READ', 'PROJECT_CONTEXT_READ', 'MNEME_CONTEXT_READ'], { WEB: 'NONE', IMPERIUM_MENTIS: 'NONE', PROJECT: 'CONTEXT_ONLY', MNEME: 'NONE' }),
  specialist('PERSONAL_LOGISTICS', 'Personal Logistics', 'Personal organization and logistics separated from projects.', 'Personal organization and logistics separated from project authority.', ['Prepare personal schedule context, travel, reminders, reservations, and errands'], ['No personal-to-production or project-to-personal sharing without future authority'], ['PERSONAL_CALENDAR_READ', 'TRAVEL_RESEARCH', 'TRAVEL_BOOK', 'RESERVATION_PREPARE', 'PERSONAL_MEMORY_READ'], { PERSONAL_CALENDAR: 'NONE', PERSONAL_MEMORY: 'NONE', PROJECT: 'NONE' })
];

const capability = (capabilityId: CapabilityId, domain: string, actionClass: ActionClass, riskClass: RiskClass, requiredSystem: string, requiredAuthority: string, mutating: boolean, availabilityEvaluator: AgentCapabilityDefinition['availabilityEvaluator'], globalAutonomyKey?: string): AgentCapabilityDefinition => ({ capabilityId, domain, actionClass, riskClass, requiredSystem, requiredAuthority, mutating, charterDeclared: true, availabilityEvaluator, globalAutonomyKey });
export const capabilityDefinitions: readonly AgentCapabilityDefinition[] = [
  capability('CALENDAR_READ', 'CALENDAR', 'READ', 'LOW', 'GOOGLE_CALENDAR', 'READ_INGRESS', false, 'GOOGLE_CALENDAR'), capability('CALENDAR_EVENT_CREATE_EXTERNAL', 'CALENDAR', 'MUTATE', 'HIGH', 'GOOGLE_CALENDAR', 'APPROVAL_BOUND_ACTION_EXECUTION_AUTHORITY', true, 'GOOGLE_CALENDAR_WRITE', 'createInternalHolds'), capability('CALENDAR_CREATE_INTERNAL_HOLD', 'CALENDAR', 'MUTATE', 'HIGH', 'GOOGLE_CALENDAR_MUTATION', 'CALENDAR_MUTATION_AUTHORITY', true, 'NOT_IMPLEMENTED', 'createInternalHolds'), capability('CALENDAR_MOVE_INTERNAL', 'CALENDAR', 'MUTATE', 'HIGH', 'GOOGLE_CALENDAR_MUTATION', 'CALENDAR_MUTATION_AUTHORITY', true, 'NOT_IMPLEMENTED', 'moveInternalMeetings'), capability('CALENDAR_MOVE_EXTERNAL', 'CALENDAR', 'MUTATE', 'CRITICAL', 'GOOGLE_CALENDAR_MUTATION', 'CALENDAR_MUTATION_AUTHORITY', true, 'NOT_IMPLEMENTED', 'moveExternalMeetings'), capability('CALENDAR_CANCEL', 'CALENDAR', 'MUTATE', 'CRITICAL', 'GOOGLE_CALENDAR_MUTATION', 'CALENDAR_MUTATION_AUTHORITY', true, 'NOT_IMPLEMENTED', 'cancelMeetings'), capability('TRAVEL_RESEARCH', 'TRAVEL', 'RESEARCH', 'MEDIUM', 'TRAVEL_PROVIDER', 'TRAVEL_RESEARCH_AUTHORITY', false, 'NOT_IMPLEMENTED'), capability('TRAVEL_BOOK', 'TRAVEL', 'MUTATE', 'CRITICAL', 'TRAVEL_PROVIDER', 'TRAVEL_BOOKING_AUTHORITY', true, 'NOT_IMPLEMENTED', 'bookTravel'),
  capability('MAIL_READ', 'COMMUNICATION', 'READ', 'LOW', 'GOOGLE_MAIL', 'READ_INGRESS', false, 'GOOGLE_MAIL'), capability('COMMUNICATION_INTERPRET', 'COMMUNICATION', 'INTERPRET', 'HIGH', 'MODEL_RUNTIME', 'REAL_SOURCE_MODEL_ACCEPTANCE', false, 'QUALITY_GATE'), capability('MAIL_DRAFT_INTERNAL', 'COMMUNICATION', 'DRAFT', 'MEDIUM', 'MAIL_DRAFT_RUNTIME', 'MAIL_DRAFT_AUTHORITY', false, 'NOT_IMPLEMENTED', 'draftInternalReplies'), capability('MAIL_SEND_INTERNAL', 'COMMUNICATION', 'MUTATE', 'HIGH', 'MAIL_SEND_RUNTIME', 'MAIL_SEND_AUTHORITY', true, 'NOT_IMPLEMENTED', 'sendInternalReplies'), capability('MAIL_DRAFT_EXTERNAL', 'COMMUNICATION', 'DRAFT', 'HIGH', 'MAIL_DRAFT_RUNTIME', 'MAIL_DRAFT_AUTHORITY', false, 'NOT_IMPLEMENTED', 'draftExternalReplies'), capability('MAIL_SEND_EXTERNAL', 'COMMUNICATION', 'MUTATE', 'CRITICAL', 'MAIL_SEND_RUNTIME', 'MAIL_SEND_AUTHORITY', true, 'NOT_IMPLEMENTED', 'sendExternalReplies'), capability('FOLLOWUP_PREPARE', 'COMMUNICATION', 'PREPARE', 'MEDIUM', 'FOLLOWUP_RUNTIME', 'FOLLOWUP_AUTHORITY', false, 'NOT_IMPLEMENTED'), capability('FOLLOWUP_SEND', 'COMMUNICATION', 'MUTATE', 'CRITICAL', 'MAIL_SEND_RUNTIME', 'FOLLOWUP_AUTHORITY', true, 'NOT_IMPLEMENTED', 'sendFollowUps'),
  capability('PROJECT_READ', 'PROJECT', 'READ', 'LOW', 'DIRECTOR_PROJECTS', 'PROJECT_READ_AUTHORITY', false, 'NOT_IMPLEMENTED'), capability('DOCUMENT_READ', 'DOCUMENT', 'READ', 'LOW', 'DIRECTOR_DOCUMENTS', 'DOCUMENT_READ_AUTHORITY', false, 'NOT_IMPLEMENTED'), capability('DOCUMENT_REQUEST_MISSING', 'DOCUMENT', 'PREPARE', 'MEDIUM', 'DIRECTOR_DOCUMENTS', 'DOCUMENT_REQUEST_AUTHORITY', false, 'NOT_IMPLEMENTED'), capability('DOCUMENT_DISTRIBUTE_APPROVED', 'DOCUMENT', 'MUTATE', 'HIGH', 'DIRECTOR_DOCUMENTS', 'DOCUMENT_DISTRIBUTE_AUTHORITY', true, 'NOT_IMPLEMENTED', 'distributeApproved'), capability('DOCUMENT_SHARE_CONFIDENTIAL', 'DOCUMENT', 'MUTATE', 'CRITICAL', 'DIRECTOR_DOCUMENTS', 'DOCUMENT_SHARE_AUTHORITY', true, 'NOT_IMPLEMENTED', 'shareConfidential'), capability('NARRATE_READ', 'NARRATE', 'READ', 'LOW', 'NARRATE', 'NARRATE_DIRECTOR_INTEGRATION', false, 'NOT_IMPLEMENTED'), capability('MNEME_CONTEXT_READ', 'MNEME', 'READ', 'LOW', 'MNEME', 'MNEME_DIRECTOR_INTEGRATION', false, 'NOT_IMPLEMENTED'),
  capability('ORDO_READ', 'ORDO', 'READ', 'LOW', 'ORDO', 'ORDO_DIRECTOR_INTEGRATION', false, 'NOT_IMPLEMENTED'), capability('PRESENCE_READ', 'PRESENCE', 'READ', 'LOW', 'PRESENCE', 'PRESENCE_DIRECTOR_INTEGRATION', false, 'NOT_IMPLEMENTED'), capability('NARRATE_CONTEXT_READ', 'NARRATE', 'READ', 'LOW', 'NARRATE', 'NARRATE_DIRECTOR_INTEGRATION', false, 'NOT_IMPLEMENTED'), capability('PRODUCTION_STATE_UPDATE', 'PRODUCTION', 'MUTATE', 'HIGH', 'ORDO', 'PRODUCTION_MUTATION_AUTHORITY', true, 'NOT_IMPLEMENTED', 'updateInternalState'), capability('PRODUCTION_DEPENDENCY_RESOLVE', 'PRODUCTION', 'MUTATE', 'HIGH', 'ORDO', 'PRODUCTION_MUTATION_AUTHORITY', true, 'NOT_IMPLEMENTED', 'resolveDependency'), capability('PRODUCTION_SCHEDULE_CHANGE', 'PRODUCTION', 'MUTATE', 'CRITICAL', 'ORDO', 'PRODUCTION_MUTATION_AUTHORITY', true, 'NOT_IMPLEMENTED', 'changeSchedule'),
  capability('WEB_RESEARCH', 'RESEARCH', 'RESEARCH', 'MEDIUM', 'WEB_RUNTIME', 'WEB_RESEARCH_AUTHORITY', false, 'NOT_IMPLEMENTED'), capability('IMPERIUM_MENTIS_READ', 'IMPERIUM_MENTIS', 'READ', 'LOW', 'IMPERIUM_MENTIS', 'IM_DIRECTOR_INTEGRATION', false, 'NOT_IMPLEMENTED'), capability('PROJECT_CONTEXT_READ', 'PROJECT', 'READ', 'LOW', 'DIRECTOR_PROJECTS', 'PROJECT_CONTEXT_AUTHORITY', false, 'NOT_IMPLEMENTED'), capability('PERSONAL_CALENDAR_READ', 'PERSONAL', 'READ', 'LOW', 'PERSONAL_CALENDAR', 'PERSONAL_CALENDAR_AUTHORITY', false, 'NOT_IMPLEMENTED'), capability('RESERVATION_PREPARE', 'PERSONAL', 'PREPARE', 'MEDIUM', 'RESERVATION_RUNTIME', 'RESERVATION_AUTHORITY', false, 'NOT_IMPLEMENTED'), capability('PERSONAL_MEMORY_READ', 'PERSONAL', 'READ', 'HIGH', 'PERSONAL_MEMORY', 'PERSONAL_MEMORY_AUTHORITY', false, 'NOT_IMPLEMENTED')
];

export const charterFor = (agentId: string) => agentCharters.find(charter => charter.agentId === agentId);
export const capabilityFor = (capabilityId: string) => capabilityDefinitions.find(capability => capability.capabilityId === capabilityId);
export const permissionRank = (value: AutonomyPermission) => ({ SUGGEST_ONLY: 0, APPROVAL_REQUIRED: 1, ALLOWED: 2 })[value];
export const minimumPermission = (global: AutonomyPermission, override?: AutonomyPermission) => !override || permissionRank(global) <= permissionRank(override) ? global : override;
