import { randomUUID } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import { CoreError } from '../core.js';
import { agentCharters, capabilityFor, charterFor, minimumPermission, permissionRank, type AgentId, type AgentStatus, type AutonomyPermission, type CapabilityAvailability, type DelegationMode, type ModelStrategy, type SourceAccess } from './contracts.js';

const json = (value: unknown) => JSON.stringify(value);
const autonomyKeys = ['createInternalHolds', 'moveInternalMeetings', 'moveExternalMeetings', 'cancelMeetings', 'draftInternalReplies', 'sendInternalReplies', 'draftExternalReplies', 'sendExternalReplies', 'sendFollowUps', 'distributeApproved', 'shareConfidential', 'updateInternalState', 'resolveDependency', 'changeSchedule', 'bookTravel'] as const;
type AutonomyKey = typeof autonomyKeys[number];
type GlobalAutonomy = Record<AutonomyKey, AutonomyPermission>;
const defaultAutonomy: GlobalAutonomy = { createInternalHolds: 'ALLOWED', moveInternalMeetings: 'APPROVAL_REQUIRED', moveExternalMeetings: 'APPROVAL_REQUIRED', cancelMeetings: 'SUGGEST_ONLY', draftInternalReplies: 'ALLOWED', sendInternalReplies: 'APPROVAL_REQUIRED', draftExternalReplies: 'ALLOWED', sendExternalReplies: 'APPROVAL_REQUIRED', sendFollowUps: 'APPROVAL_REQUIRED', distributeApproved: 'APPROVAL_REQUIRED', shareConfidential: 'SUGGEST_ONLY', updateInternalState: 'ALLOWED', resolveDependency: 'APPROVAL_REQUIRED', changeSchedule: 'SUGGEST_ONLY', bookTravel: 'SUGGEST_ONLY' };
const defaultChief = { proactivity: 'BALANCED', dailyBrief: false, dailyBriefTime: '08:00', endOfDayReview: false, endOfDayReviewTime: '18:30', autoMeetingPrep: false, meetingPrepMinutes: 60, followUpThresholdHours: 24 };
const sourceRank = (value: SourceAccess) => ({ NONE: 0, CONTEXT_ONLY: 1, READ: 2 })[value];
const current = (value: unknown) => value && typeof value === 'object' ? value as Record<string, unknown> : {};

export interface OperatorControlPatch { version: number; globalPause?: boolean; globalAutonomy?: Partial<GlobalAutonomy>; chiefOfStaff?: Partial<typeof defaultChief>; actor?: { id: string; displayName: string }; }
export interface AgentPolicyPatch { version: number; status?: AgentStatus; delegationMode?: DelegationMode; modelStrategy?: ModelStrategy; capabilityOverrides?: Record<string, AutonomyPermission | null>; sourceScopeOverrides?: Record<string, SourceAccess | null>; actor?: { id: string; displayName: string }; }

export class AgentOperatorControlService {
  constructor(private readonly db: Pool) {}
  private async ensureDefaults() {
    await this.db.query('insert into director_operator_controls(singleton,global_autonomy,chief_of_staff) values(true,$1,$2) on conflict(singleton) do nothing', [json(defaultAutonomy), json(defaultChief)]);
    for (const charter of agentCharters) await this.db.query('insert into director_agent_operator_policies(agent_id,status,delegation_mode,model_strategy) values($1,$2,$3,$4) on conflict(agent_id) do nothing', [charter.agentId, charter.defaultOperatorPolicy.status, charter.defaultOperatorPolicy.delegationMode, charter.defaultOperatorPolicy.modelStrategy]);
  }
  private controls(row: any) { return { globalAutonomy: { ...defaultAutonomy, ...current(row.global_autonomy) } as GlobalAutonomy, chiefOfStaff: { ...defaultChief, ...current(row.chief_of_staff) }, globalPause: row.global_pause, version: row.version, updatedAt: row.updated_at?.toISOString() }; }
  private policy(row: any, capabilityOverrides: Record<string, AutonomyPermission>, sourceScopeOverrides: Record<string, SourceAccess>) { return { agentId: row.agent_id as AgentId, status: row.status as AgentStatus, delegationMode: row.delegation_mode as DelegationMode, modelStrategy: row.model_strategy as ModelStrategy, capabilityOverrides, sourceScopeOverrides, version: row.version, updatedAt: row.updated_at?.toISOString() }; }
  private async policies() {
    await this.ensureDefaults();
    const [policyRows, capRows, scopeRows] = await Promise.all([this.db.query('select * from director_agent_operator_policies order by agent_id'), this.db.query('select * from director_agent_capability_overrides'), this.db.query('select * from director_agent_source_scope_overrides')]);
    const caps = new Map<string, Record<string, AutonomyPermission>>(); const scopes = new Map<string, Record<string, SourceAccess>>();
    for (const row of capRows.rows) caps.set(row.agent_id, { ...(caps.get(row.agent_id) ?? {}), [row.capability_id]: row.permission });
    for (const row of scopeRows.rows) scopes.set(row.agent_id, { ...(scopes.get(row.agent_id) ?? {}), [row.source_scope]: row.access_level });
    return policyRows.rows.map(row => this.policy(row, caps.get(row.agent_id) ?? {}, scopes.get(row.agent_id) ?? {}));
  }
  async getControls() { await this.ensureDefaults(); return this.controls((await this.db.query('select * from director_operator_controls where singleton=true')).rows[0]); }
  async updateControls(patch: OperatorControlPatch) {
    if (Object.keys(patch.globalAutonomy ?? {}).some(key => !(autonomyKeys as readonly string[]).includes(key))) throw new CoreError('GLOBAL_AUTONOMY_KEY_FORBIDDEN', 422, 'Unknown global autonomy key');
    await this.ensureDefaults();
    const client = await this.db.connect(); const actor = patch.actor ?? { id: 'operator', displayName: 'Operator' }; const correlationId = randomUUID();
    try { await client.query('begin'); const existing = this.controls((await client.query('select * from director_operator_controls where singleton=true for update')).rows[0]); if (existing.version !== patch.version) throw new CoreError('STALE_POLICY_VERSION', 409, 'Operator controls changed; reload before saving');
      const globalAutonomy = { ...existing.globalAutonomy, ...(patch.globalAutonomy ?? {}) }; const chiefOfStaff = { ...existing.chiefOfStaff, ...(patch.chiefOfStaff ?? {}) }; const globalPause = patch.globalPause ?? existing.globalPause;
      await client.query('update director_operator_controls set global_autonomy=$1,chief_of_staff=$2,global_pause=$3,version=version+1,updated_at=now() where singleton=true', [json(globalAutonomy), json(chiefOfStaff), globalPause]);
      for (const [key, next] of Object.entries({ ...patch.globalAutonomy, ...patch.chiefOfStaff, ...(patch.globalPause === undefined ? {} : { globalPause }) })) await this.event(client, actor, key === 'globalPause' ? globalPause ? 'GLOBAL_PAUSE_ENABLED' : 'GLOBAL_PAUSE_DISABLED' : 'GLOBAL_AUTONOMY_CHANGED', undefined, key, key === 'globalPause' ? existing.globalPause : (existing.globalAutonomy as any)[key] ?? (existing.chiefOfStaff as any)[key], next, correlationId);
      await client.query('commit'); return this.getControls();
    } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); }
  }
  async getAgent(agentId: string) { const charter = charterFor(agentId); if (!charter) throw new CoreError('AGENT_NOT_FOUND', 404, 'Agent is not defined'); const [controls, policies] = await Promise.all([this.getControls(), this.policies()]); const policy = policies.find(item => item.agentId === charter.agentId)!; const connection = await this.connectionFacts(); return this.project(charter.agentId, charter, policy, controls, connection); }
  async listAgents() { const [controls, policies, connection] = await Promise.all([this.getControls(), this.policies(), this.connectionFacts()]); return agentCharters.map(charter => this.project(charter.agentId, charter, policies.find(item => item.agentId === charter.agentId)!, controls, connection)); }
  async getCapabilities(agentId: string) { return (await this.getAgent(agentId)).capabilities; }
  async updateAgentPolicy(agentId: string, patch: AgentPolicyPatch) {
    const charter = charterFor(agentId); if (!charter) throw new CoreError('AGENT_NOT_FOUND', 404, 'Agent is not defined'); await this.ensureDefaults();
    const client = await this.db.connect(); const actor = patch.actor ?? { id: 'operator', displayName: 'Operator' }; const correlationId = randomUUID();
    try { await client.query('begin'); const row = (await client.query('select * from director_agent_operator_policies where agent_id=$1 for update', [agentId])).rows[0]; if (row.version !== patch.version) throw new CoreError('STALE_POLICY_VERSION', 409, 'Agent policy changed; reload before saving'); if (charter.cannotDisable && patch.status === 'PAUSED') throw new CoreError('CHIEF_OF_STAFF_CANNOT_DISABLE', 422, 'Chief of Staff can only be paused by global Pause All');
      const caps = (await client.query('select capability_id,permission from director_agent_capability_overrides where agent_id=$1', [agentId])).rows.reduce((acc, item) => ({ ...acc, [item.capability_id]: item.permission }), {} as Record<string, AutonomyPermission>);
      const scopes = (await client.query('select source_scope,access_level from director_agent_source_scope_overrides where agent_id=$1', [agentId])).rows.reduce((acc, item) => ({ ...acc, [item.source_scope]: item.access_level }), {} as Record<string, SourceAccess>);
      const controls = this.controls((await client.query('select * from director_operator_controls where singleton=true')).rows[0]);
      for (const [capabilityId, override] of Object.entries(patch.capabilityOverrides ?? {})) { const definition = capabilityFor(capabilityId); if (!definition || !charter.declaredCapabilities.includes(capabilityId as any) || !definition.globalAutonomyKey) throw new CoreError('CAPABILITY_OVERRIDE_FORBIDDEN', 422, 'Capability override is not declared by this charter'); if (override === null) { await client.query('delete from director_agent_capability_overrides where agent_id=$1 and capability_id=$2', [agentId, capabilityId]); delete caps[capabilityId]; continue; } const global = controls.globalAutonomy[definition.globalAutonomyKey as AutonomyKey]; if (permissionRank(override) > permissionRank(global)) throw new CoreError('AGENT_POLICY_CANNOT_ESCALATE', 422, 'Cannot exceed global autonomy'); await client.query('insert into director_agent_capability_overrides(agent_id,capability_id,permission) values($1,$2,$3) on conflict(agent_id,capability_id) do update set permission=excluded.permission,updated_at=now()', [agentId, capabilityId, override]); caps[capabilityId] = override; await this.event(client, actor, 'AGENT_CAPABILITY_RESTRICTED', agentId, capabilityId, undefined, override, correlationId); }
      for (const [scope, override] of Object.entries(patch.sourceScopeOverrides ?? {})) { const charterAccess = charter.sourceScopes[scope]; if (!charterAccess) throw new CoreError('SOURCE_SCOPE_OVERRIDE_FORBIDDEN', 422, 'Source scope is not declared by this charter'); if (override === null) { await client.query('delete from director_agent_source_scope_overrides where agent_id=$1 and source_scope=$2', [agentId, scope]); delete scopes[scope]; continue; } if (sourceRank(override) > sourceRank(charterAccess)) throw new CoreError('AGENT_SOURCE_CANNOT_ESCALATE', 422, 'Cannot exceed charter source access'); await client.query('insert into director_agent_source_scope_overrides(agent_id,source_scope,access_level) values($1,$2,$3) on conflict(agent_id,source_scope) do update set access_level=excluded.access_level,updated_at=now()', [agentId, scope, override]); scopes[scope] = override; await this.event(client, actor, 'AGENT_SOURCE_ACCESS_RESTRICTED', agentId, scope, undefined, override, correlationId); }
      const status = patch.status ?? row.status; const delegationMode = patch.delegationMode ?? row.delegation_mode; const modelStrategy = patch.modelStrategy ?? row.model_strategy; await client.query('update director_agent_operator_policies set status=$2,delegation_mode=$3,model_strategy=$4,version=version+1,updated_at=now() where agent_id=$1', [agentId, status, delegationMode, modelStrategy]);
      if (patch.status && patch.status !== row.status) await this.event(client, actor, patch.status === 'PAUSED' ? 'AGENT_PAUSED' : 'AGENT_RESUMED', agentId, 'status', row.status, patch.status, correlationId); if (patch.modelStrategy && patch.modelStrategy !== row.model_strategy) await this.event(client, actor, 'MODEL_STRATEGY_CHANGED', agentId, 'modelStrategy', row.model_strategy, patch.modelStrategy, correlationId);
      await client.query('commit'); return this.getAgent(agentId);
    } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); }
  }
  async events() { await this.ensureDefaults(); return (await this.db.query('select id,occurred_at,actor,event_type,agent_id,policy_key,previous_value,new_value,correlation_id,provenance from director_agent_policy_events order by occurred_at desc')).rows; }
  private async event(client: PoolClient, actor: { id: string; displayName: string }, eventType: string, agentId: string | undefined, policyKey: string, previous: unknown, next: unknown, correlationId: string) { await client.query('insert into director_agent_policy_events(id,actor,event_type,agent_id,policy_key,previous_value,new_value,correlation_id,provenance) values($1,$2,$3,$4,$5,$6,$7,$8,$9)', [randomUUID(), json({ kind: 'HUMAN_OPERATOR', id: actor.id, displayName: actor.displayName }), eventType, agentId ?? null, policyKey, previous === undefined ? null : json(previous), next === undefined ? null : json(next), correlationId, json({ authority: 'NE_DIRECTOR_AGENT_CHARTER_CAPABILITY_AND_OPERATOR_CONTROL_AUTHORITY_001', safe_policy_only: true })]); }
  private async connectionFacts() { const result = await this.db.query("select capability,connection_state,enabled from director_source_accounts where provider='GOOGLE'"); return { mail: result.rows.some(row => row.capability === 'COMMUNICATION' && row.enabled && row.connection_state === 'CONNECTED'), calendar: result.rows.some(row => row.capability === 'SCHEDULE' && row.enabled && row.connection_state === 'CONNECTED') }; }
  private project(agentId: AgentId, charter: ReturnType<typeof charterFor> & {}, policy: any, controls: ReturnType<AgentOperatorControlService['controls']>, connection: { mail: boolean; calendar: boolean }) {
    const sourceIsConnected = (scope: string) => scope === 'MAIL' ? connection.mail : scope === 'CALENDAR' ? connection.calendar : false;
    const requestedSourceAccess = Object.fromEntries(Object.entries(charter.sourceScopes).map(([scope, charterAccess]) => [scope, policy.sourceScopeOverrides[scope] ?? charterAccess]));
    const sourceAccess = Object.fromEntries(Object.entries(requestedSourceAccess).map(([scope, requested]) => [scope, sourceIsConnected(scope) ? requested : 'NONE']));
    const capabilities = charter.declaredCapabilities.map(capabilityId => { const definition = capabilityFor(capabilityId)!; let availability: CapabilityAvailability = definition.availabilityEvaluator === 'GOOGLE_MAIL' ? connection.mail ? 'AVAILABLE' : 'NOT_CONNECTED' : definition.availabilityEvaluator === 'GOOGLE_CALENDAR' ? connection.calendar ? 'AVAILABLE' : 'NOT_CONNECTED' : definition.availabilityEvaluator === 'QUALITY_GATE' ? 'QUALITY_BLOCKED' : 'NOT_IMPLEMENTED'; const global = definition.globalAutonomyKey ? controls.globalAutonomy[definition.globalAutonomyKey as AutonomyKey] : 'SUGGEST_ONLY'; const override = policy.capabilityOverrides[capabilityId]; const effectiveAutonomy = minimumPermission(global, override); let effectiveState: CapabilityAvailability = availability; let limitingReason = availability === 'QUALITY_BLOCKED' ? 'No model has passed the frozen real-source interpretation quality gate.' : availability === 'NOT_CONNECTED' ? 'Required source system is not connected and proven.' : availability === 'NOT_IMPLEMENTED' ? 'Required integration or authority is not implemented.' : undefined; if (controls.globalPause) { effectiveState = 'OPERATOR_PAUSED'; limitingReason = 'Global Pause All is enabled.'; } else if (policy.status === 'PAUSED' && agentId !== 'CHIEF_OF_STAFF') { effectiveState = 'AGENT_PAUSED'; limitingReason = 'Agent is paused by the operator.'; } else if (definition.globalAutonomyKey && availability === 'AVAILABLE' && effectiveAutonomy === 'SUGGEST_ONLY') { effectiveState = 'POLICY_BLOCKED'; limitingReason = 'Global or agent policy restricts this capability to suggestions.'; } return { ...definition, availability, effectiveState, effectiveAutonomy, operatorOverride: override, limitingReason, executable: false }; });
    const derivedState = controls.globalPause ? 'OPERATOR_PAUSED' : policy.status === 'PAUSED' && agentId !== 'CHIEF_OF_STAFF' ? 'PAUSED' : capabilities.length && capabilities.every(capability => capability.availability !== 'AVAILABLE') ? 'CAPABILITY_LIMITED' : 'ACTIVE';
    return { charter, operatorPolicy: policy, sourceAccess, requestedSourceAccess, derivedState, globalPause: controls.globalPause, capabilities, effectiveCapabilitySummary: { available: capabilities.filter(item => item.availability === 'AVAILABLE').length, limited: capabilities.filter(item => item.availability !== 'AVAILABLE').length }, runtimeAuthority: 'INTERNAL_READ_PREPARATION_ONLY' };
  }
  async authorizeAgentWork(agentId: string, requiredCapabilities: string[]) {
    const agent = await this.getAgent(agentId);
    if (agent.globalPause || agent.operatorPolicy.status === 'PAUSED') throw new CoreError('AGENT_RUNTIME_POLICY_BLOCKED', 409, agent.globalPause ? 'Global Pause All is enabled' : 'Agent is paused');
    for (const capabilityId of requiredCapabilities) {
      const capability = agent.capabilities.find(item => item.capabilityId === capabilityId);
      if (!capability || capability.availability !== 'AVAILABLE' || capability.effectiveState !== 'AVAILABLE') throw new CoreError(capability?.availability === 'QUALITY_BLOCKED' ? 'QUALITY_BLOCKED' : 'AGENT_RUNTIME_CAPABILITY_BLOCKED', 409, capability?.limitingReason ?? 'Required capability is unavailable');
    }
    return agent;
  }
}
