import { createHash, randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import { CoreError } from '../core.js';
import { AgentOperatorControlService } from '../agents/service.js';
import type { CalendarEventCreatePayload, CalendarMutationProvider, ExternalActionStatus } from './contracts.js';

const json = (value: unknown) => JSON.stringify(value);
const hash = (value: unknown) => createHash('sha256').update(json(value)).digest('hex');
const event = (db: Pool, actionId: string, eventType: string, actor: unknown, detail: unknown, correlationId = randomUUID()) => db.query('insert into director_external_action_events(id,action_id,event_type,actor,detail,correlation_id,provenance) values($1,$2,$3,$4,$5,$6,$7)', [randomUUID(), actionId, eventType, actor ? json(actor) : null, json(detail), correlationId, json({ authority: 'NE_DIRECTOR_APPROVAL_BOUND_ACTION_EXECUTION_AND_PROVIDER_RECEIPT_AUTHORITY_001', safe_metadata_only: true })]);
const actor = (input?: { id: string; displayName: string }) => input ?? { id: 'operator', displayName: 'Operator' };

export class ApprovalBoundActionService {
  readonly controls: AgentOperatorControlService;
  constructor(private readonly db: Pool, private readonly calendar: CalendarMutationProvider) { this.controls = new AgentOperatorControlService(db); }
  async proposeCalendarCreate(input: { connectionId: string; payload: CalendarEventCreatePayload; workItemId?: string; artifactId?: string; createdBy?: { id: string; displayName: string } }) {
    if (input.payload.attendees.length || !input.payload.title || !input.payload.calendarId || Number.isNaN(Date.parse(input.payload.startsAt)) || Number.isNaN(Date.parse(input.payload.endsAt)) || Date.parse(input.payload.endsAt) <= Date.parse(input.payload.startsAt)) throw new CoreError('ACTION_PAYLOAD_INVALID', 422, 'Calendar create payload is invalid');
    const connection = await this.db.query("select id,provider,enabled,authorization_state,authorization_scopes from director_connections where id=$1", [input.connectionId]); if (!connection.rowCount || connection.rows[0].provider !== 'GOOGLE') throw new CoreError('ACTION_PROVIDER_NOT_AVAILABLE', 409, 'Google Calendar connection is required');
    const id = randomUUID(); const payloadHash = hash(input.payload); await this.db.query("insert into director_external_actions(id,action_type,owning_agent_id,capability_id,provider_connection_id,source_work_item_id,source_artifact_id,payload,payload_hash,approval_requirement,status,created_by,provider_idempotency_key,provenance) values($1,'CALENDAR_EVENT_CREATE','CALENDAR_TRAVEL','CALENDAR_EVENT_CREATE_EXTERNAL',$2,$3,$4,$5,$6,'APPROVAL_REQUIRED','AWAITING_APPROVAL',$7,$8,$9)", [id,input.connectionId,input.workItemId??null,input.artifactId??null,json(input.payload),payloadHash,json(actor(input.createdBy)),`calendar-create:${id}`,json({ provider: 'GOOGLE', no_attendees: true })]); await event(this.db,id,'ACTION_PROPOSED',actor(input.createdBy),{ actionType:'CALENDAR_EVENT_CREATE', payloadHash }); return this.get(id);
  }
  async approve(id: string, input: { actor?: { id: string; displayName: string }; rationale?: string }) { const client=await this.db.connect(); try { await client.query('begin'); const result=await client.query('select * from director_external_actions where id=$1 for update',[id]); if(!result.rowCount) throw new CoreError('NOT_FOUND',404,'Action not found'); const action=result.rows[0]; if(action.status!=='AWAITING_APPROVAL') throw new CoreError('ACTION_NOT_AWAITING_APPROVAL',409,'Action cannot be approved'); const a=actor(input.actor); const correlationId=randomUUID(); await client.query("insert into director_external_action_approvals(id,action_id,action_version,payload_hash,operator_actor,decision,rationale,correlation_id,provenance) values($1,$2,$3,$4,$5,'APPROVE',$6,$7,$8)",[randomUUID(),id,action.action_version,action.payload_hash,json(a),input.rationale??null,correlationId,json({immutable_binding:true})]); await client.query("update director_external_actions set status='APPROVED',approved_at=now() where id=$1",[id]); await event(client as any,id,'ACTION_APPROVED',a,{actionVersion:action.action_version,payloadHash:action.payload_hash},correlationId); await client.query('commit'); return this.get(id); } catch(error){await client.query('rollback');throw error;} finally {client.release();} }
  async reject(id: string,input:{actor?:{id:string;displayName:string};rationale?:string}) { const current=await this.get(id); if(current.status!=='AWAITING_APPROVAL') throw new CoreError('ACTION_NOT_AWAITING_APPROVAL',409,'Action cannot be rejected'); const a=actor(input.actor); const correlationId=randomUUID(); await this.db.query("insert into director_external_action_approvals(id,action_id,action_version,payload_hash,operator_actor,decision,rationale,correlation_id,provenance) values($1,$2,$3,$4,$5,'REJECT',$6,$7,$8)",[randomUUID(),id,current.action_version,current.payload_hash,json(a),input.rationale??null,correlationId,json({immutable_binding:true})]); await this.db.query("update director_external_actions set status='CANCELLED' where id=$1",[id]); await event(this.db,id,'ACTION_REJECTED',a,{actionVersion:current.action_version},correlationId); return this.get(id); }
  async execute(id:string) { const client=await this.db.connect(); let action:any; try { await client.query('begin'); const found=await client.query("select a.*,p.payload_hash approval_hash,p.action_version approval_version from director_external_actions a join director_external_action_approvals p on p.action_id=a.id and p.decision='APPROVE' where a.id=$1 for update",[id]); if(!found.rowCount) throw new CoreError('ACTION_APPROVAL_REQUIRED',409,'A matching approval is required'); action=found.rows[0]; if(action.status!=='APPROVED'||action.action_version!==action.approval_version||action.payload_hash!==action.approval_hash) throw new CoreError('ACTION_APPROVAL_STALE',409,'Approval is not bound to current action payload'); await client.query("update director_external_actions set status='EXECUTING',execution_started_at=now(),lease_owner=$2,lease_expires_at=now()+interval '60 seconds' where id=$1",[id,`action-${process.pid}`]); await event(client as any,id,'ACTION_EXECUTION_STARTED',null,{actionVersion:action.action_version}); await client.query('commit'); } catch(error){await client.query('rollback');throw error;} finally{client.release();}
    try { await this.reauthorize(action); const receipt=await this.calendar.createEvent(action.provider_connection_id,id,action.payload); const verify=await this.calendar.verifyEvent(action.provider_connection_id,receipt); if(!verify) throw new CoreError('ACTION_RECEIPT_VERIFICATION_FAILED',502,'Calendar receipt could not be verified'); const c=await this.db.connect(); try{await c.query('begin');await c.query('insert into director_provider_receipts(id,action_id,action_version,provider,connection_id,remote_event_id,remote_calendar_id,provider_revision,provider_status,executed_at,payload_hash,provider_request_correlation,provenance) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[randomUUID(),id,action.action_version,receipt.provider,receipt.connectionId,receipt.remoteEventId,receipt.remoteCalendarId,receipt.providerRevision??null,receipt.providerStatus??null,receipt.executedAt,action.payload_hash,receipt.providerRequestCorrelation??null,json({read_after_write_verified:true})]);await event(c as any,id,'ACTION_PROVIDER_ACCEPTED',null,{remoteEventId:receipt.remoteEventId});await event(c as any,id,'ACTION_RECEIPT_RECORDED',null,{remoteEventId:receipt.remoteEventId});await c.query("update director_external_actions set status='SUCCEEDED',succeeded_at=now(),lease_owner=null,lease_expires_at=null where id=$1",[id]);await event(c as any,id,'ACTION_SUCCEEDED',null,{receipt:true});await c.query('commit');}catch(error){await c.query('rollback');throw error;}finally{c.release();} return this.get(id); } catch(error){const code=error instanceof CoreError?error.code:'ACTION_OUTCOME_UNKNOWN'; const status:ExternalActionStatus=code==='ACTION_PROVIDER_RECEIPT_INVALID'||code==='ACTION_RECEIPT_VERIFICATION_FAILED'?'OUTCOME_UNKNOWN':code.includes('POLICY')?'BLOCKED_POLICY':code.includes('CAPABILITY')||code.includes('AUTH')||code.includes('CONFIGURATION')?'BLOCKED_CAPABILITY':'OUTCOME_UNKNOWN'; await this.db.query('update director_external_actions set status=$2,failure_code=$3,lease_owner=null,lease_expires_at=null where id=$1',[id,status,code]);await event(this.db,id,status==='OUTCOME_UNKNOWN'?'ACTION_OUTCOME_UNKNOWN':'ACTION_FAILED',null,{code});throw error;}
  }
  private async reauthorize(action:any) { const controls=await this.controls.getControls(); if(controls.globalPause) throw new CoreError('ACTION_POLICY_BLOCKED',409,'Global Pause All is enabled'); const agent=await this.controls.getAgent('CALENDAR_TRAVEL'); const capability=agent.capabilities.find((x:any)=>x.capabilityId==='CALENDAR_EVENT_CREATE_EXTERNAL'); if(agent.operatorPolicy.status!=='ACTIVE'||!capability||capability.availability!=='AVAILABLE'||capability.effectiveState!=='AVAILABLE') throw new CoreError('ACTION_CAPABILITY_BLOCKED',409,'Calendar write authority is unavailable'); const connection=await this.db.query("select enabled,authorization_state,connection_state,authorization_scopes from director_connections where id=$1",[action.provider_connection_id]); if(!connection.rowCount||!connection.rows[0].enabled||connection.rows[0].authorization_state!=='AUTHORIZED'||connection.rows[0].connection_state!=='CONNECTED'||!connection.rows[0].authorization_scopes.includes('https://www.googleapis.com/auth/calendar.events')) throw new CoreError('ACTION_CAPABILITY_BLOCKED',409,'Calendar write connection is unavailable'); }
  async get(id:string){const result=await this.db.query('select * from director_external_actions where id=$1',[id]);if(!result.rowCount)throw new CoreError('NOT_FOUND',404,'Action not found');return result.rows[0];}
  async list(){return (await this.db.query('select * from director_external_actions order by created_at desc')).rows;}
  async receipts(id:string){return (await this.db.query('select * from director_provider_receipts where action_id=$1 order by executed_at desc',[id])).rows;}
}
